version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Test
          command: make test
workflows:
  version: 2
  test:
    jobs:
      - test
